# Package the Windows app as a portable directory + (optionally) an Inno Setup installer.
#
# Usage:
#   .\tool\package_windows.ps1 [-Sign] [-Inno "C:\Program Files (x86)\Inno Setup 6\ISCC.exe"]
#
# Prereqs:
#   - Flutter desktop enabled, Visual Studio Build Tools installed
#   - cargo on PATH (rustup default-toolchain stable)
#   - (optional) Inno Setup 6 for installer generation

param(
    [switch] $Sign,
    [string] $Inno = ""
)

$ErrorActionPreference = "Stop"
$Root = Resolve-Path (Join-Path $PSScriptRoot "..")
$BackendDir = Resolve-Path (Join-Path $Root "..\backend")

Write-Host "==> Building Rust backend (release, x86_64-pc-windows-msvc)"
Push-Location $BackendDir
& rustup target add x86_64-pc-windows-msvc | Out-Null
& cargo build --release --target x86_64-pc-windows-msvc -p omnibot-backend
if ($LASTEXITCODE -ne 0) { throw "cargo build failed" }
$BinaryPath = Join-Path $BackendDir "target\x86_64-pc-windows-msvc\release\omnibot-backend.exe"
Pop-Location

Write-Host "==> Flutter release build"
Push-Location $Root
& flutter build windows --release
if ($LASTEXITCODE -ne 0) { throw "flutter build failed" }
Pop-Location

$ReleaseDir = Join-Path $Root "build\windows\x64\runner\Release"
Copy-Item -Force $BinaryPath (Join-Path $ReleaseDir "omnibot-backend.exe")

if ($Sign) {
    Write-Host "==> SignTool not configured; skipping. Add your signtool.exe path here."
}

if (-not [string]::IsNullOrEmpty($Inno)) {
    if (-not (Test-Path $Inno)) { throw "Inno Setup compiler not found at $Inno" }
    $IssPath = Join-Path $PSScriptRoot "omnibot_installer.iss"
    if (-not (Test-Path $IssPath)) {
        Write-Host "==> Generating Inno Setup script"
        @"
; Auto-generated by package_windows.ps1
[Setup]
AppName=Omnibot
AppVersion=0.1.0
DefaultDirName={pf}\Omnibot
DefaultGroupName=Omnibot
UninstallDisplayIcon={app}\omnibot_desktop_runner.exe
OutputBaseFilename=omnibot-installer
Compression=lzma2
SolidCompression=yes

[Files]
Source: "$ReleaseDir\*"; DestDir: "{app}"; Flags: recursesubdirs ignoreversion

[Icons]
Name: "{group}\Omnibot"; Filename: "{app}\omnibot_desktop_runner.exe"
Name: "{commondesktop}\Omnibot"; Filename: "{app}\omnibot_desktop_runner.exe"; Tasks: desktopicon

[Tasks]
Name: "desktopicon"; Description: "Create a desktop icon"
"@ | Set-Content -Encoding UTF8 $IssPath
    }
    Write-Host "==> Running Inno Setup compiler"
    & $Inno $IssPath
}

Write-Host "==> Done. Portable build directory: $ReleaseDir"
